name: CI - bootcamp-devops-project1 - web - dev
on:
  push:
    branches: [ "development" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}      
      -
        name: Build and push - Web
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: abalderasp/bootcamp-devops-web:${{ github.sha }}
          
      - name: "Git checkout"
        uses: "actions/checkout@v2"
        with:
          token: ${{ secrets.ACTIONS_SYSTEM_USER }}
    
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
          
      - name: Update Kubernetes resources - web
        run: |
          cd gitops-bootcamp/web/
          kustomize edit set image abalderasp/bootcamp-devops-web=abalderasp/bootcamp-devops-web:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit files
        run: |
          git config --local user.email "abalderas@occ.com.mx"
          git config --local user.name "abalderasp"
          git commit -am "rolling image to tag $GITHUB_SHA"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTIONS_SYSTEM_USER }}
          branch: ${{ github.ref }}
      